POST https://cblife.axra.app/dashboard/api/news
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbi0xIiwiaWF0IjoxNjc5Mjc1OTY2LCJleHAiOjE2NzkzMTkxNjZ9.Dp0nP7K_okiqnrp_AUzajl0hDYzjaDf2kRC8n_N0FM4

{
    "image": "http://....",
    "title": "မြန်မာနိုင်ငံ",
    "paragraph": "မြန်မာနိုင်ငံရှိအစောဆုံးသော အခြေချမှုများသည် ပျူမြို့ပြနိုင်ငံများနှင့် မွန်ဘုရင့်နိုင်ငံများ၌ဖြစ်ကြသည်။[၉] အေဒီ ၉ရာစုခန့်တွင် မြန်မာလူမျိုးတို့သည် ဧရာဝတီမြစ်အနီး၌ ပုဂံပြည်ကိုတည်ထောင်ခဲ့ကြရာ မြန်မာ့ယဉ်ကျေးမှု၊ မြန်မာဘာသာစကားစသည်တို့ ပေါ်ပေါက်လာခဲ့သည်။ ပထမမြန်မာနိုင်ငံတော် ပုဂံပြည်သည် မွန်ဂိုကျူးကျော်စစ်ကြောင့် ကျဆုံးခဲ့ရသည်။ ၁၆ ရာစု‌တွင် ဒုတိယမြန်မာနိုင်ငံတော် တောင်ငူအင်ပါယာပေါ်ပေါက်လာခဲ့ပြီး အရှေ့တောင်အာရှသမိုင်း၏ အကြီးဆုံးအင်ပါယာအဖြစ် ခေတ္တရပ်တည်နိုင်ခဲ့သည်။[၁၀] ၁၉ ရာစုတွင် တတိယမြန်မာနိုင်ငံတော် ကုန်းဘောင်အင်ပါယာသည်"
}